# Generated by Django 6.0.5 on 2026-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hisob nomi')),
                ('account_type', models.CharField(choices=[('cash', 'Kassa'), ('bank', 'Bank/Karta')], default='cash', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Balans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('category_type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], default='expense', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
