# Generated by Django 6.0.5 on 2026-07-18 23:36

import django.db.models.deletion
from django.db import migrations, models


def populate_roles_and_employee_links(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    Role = apps.get_model('employee', 'Role')

    role_map = {
        'WAITER': ('waiter', 'Ofitsiant'),
        'KITCHEN': ('kitchen', 'Oshpaz'),
        'CASHIER': ('cashier', 'Kassir'),
        'MANAGER': ('manager', 'Menejer'),
        'ADMIN': ('admin', 'Administrator'),
    }

    for role_name, (slug, label) in role_map.items():
        Role.objects.get_or_create(name=slug, defaults={'label': label})

    for employee in Employee.objects.all():
        old_value = getattr(employee, 'role', '') or ''
        if not old_value:
            continue

        normalized = str(old_value).upper()
        if normalized not in role_map:
            continue

        role_slug, _ = role_map[normalized]
        role = Role.objects.get(name=role_slug)
        employee.role = str(role.pk)
        employee.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RunPython(populate_roles_and_employee_links, migrations.RunPython.noop),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.role'),
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_type', models.CharField(choices=[('monthly', 'Oylik'), ('hourly', 'Soatlik'), ('bonus', 'Bonus'), ('commission', 'Komissiya')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('review', 'Tekshirilmoqda'), ('approved', 'Tasdiqlangan'), ('paid', 'To‘langan')], default='draft', max_length=20)),
                ('period', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard (Asosiy sahifa)'), ('pos_system', 'Savdo paneli (POS Tizimi)'), ('orders', "Buyurtmalar ro'yxati"), ('products', 'Taomlar va Menyu'), ('inventory', 'Ombor va Inventar (Xomashyo)'), ('employees', 'Xodimlar boshqaruvi'), ('settings', 'Tizim Sozlamalari (Filiallar)')], max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='employee.role')),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
