# Generated by Django 6.0.5 on 2026-07-29 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_role_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sxema nomi')),
                ('scheme_type', models.CharField(choices=[('fixed', 'Fiksalangan'), ('hourly', 'Soatbay'), ('percent', 'Foizli'), ('mixed', 'Aralash')], default='fixed', max_length=20)),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sales_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_schemes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
