# Generated by Django 6.0.5 on 2026-08-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_salaryscheme'),
        ('sozlamalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='sozlamalar.branch'),
        ),
    ]
