# Generated by Django 6.0.5 on 2026-07-17 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hisob nomi')),
                ('account_type', models.CharField(choices=[('CASH', 'Naqd'), ('BANK', 'Naqd pulsiz')], default='CASH', max_length=50, verbose_name='Hisob turi')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Qoldiq')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moliyaviy Hisob',
                'verbose_name_plural': 'Moliyaviy Hisoblar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('category_type', models.CharField(choices=[('INCOME', 'Daromad'), ('EXPENSE', 'Xarajat')], max_length=50, verbose_name='Kategoriya turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moliyaviy Kategoriya',
                'verbose_name_plural': 'Moliyaviy Kategoriyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shtrix-kod')),
                ('mxik', models.CharField(blank=True, max_length=100, null=True, verbose_name='MXIK')),
                ('unit', models.CharField(max_length=50, verbose_name="O'lchov birligi")),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name="Bo'lim / Kategoriya")),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahsulot turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_products/', verbose_name='Mahsulot rasmi')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('is_measured', models.BooleanField(default=False, verbose_name="O'lchovli")),
                ('is_marked', models.BooleanField(default=False, verbose_name='Markirovka')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotish narxi')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ulgurji narx')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sotib olish narxi')),
                ('margin_percent', models.FloatField(default=0.0, verbose_name='Ustama %')),
                ('qqs_rate', models.CharField(blank=True, max_length=50, null=True, verbose_name='QQS stavkasi')),
                ('min_wholesale_qty', models.FloatField(default=0.0, verbose_name='Ulgurji sotuv uchun minimal miqdor')),
                ('min_stock', models.FloatField(default=0.0, verbose_name='Minimal qoldiq')),
                ('max_stock', models.FloatField(default=0.0, verbose_name='Maksimal qoldiq')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ishlab chiqaruvchi')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ishlab chiqarilgan davlat')),
                ('atc_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='ATC')),
                ('mhh_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='MHH')),
                ('pack_quantity', models.FloatField(default=0.0, verbose_name='Qadoqdagi miqdor')),
                ('allow_piece_sale', models.BooleanField(default=False, verbose_name='Donalab sotishga ruxsat berish')),
                ('by_recipe', models.BooleanField(default=False, verbose_name="Retsept bo'yicha")),
                ('is_commission', models.BooleanField(default=False, verbose_name='Komissiya')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('current_stock', models.FloatField(default=0.0, verbose_name='Ombordagi joriy zaxira')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OlchovBirligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "O'lchov birligi",
                'verbose_name_plural': "O'lchov birliklari",
            },
        ),
        migrations.CreateModel(
            name='OvqatKategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ovqat kategoriyasi',
                'verbose_name_plural': 'Ovqat kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Ombor')),
                ('supplier', models.CharField(max_length=255, verbose_name="Ta'minotchi")),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hujjat raqami')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shartnoma raqami')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Tushum summasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Ombor')),
                ('agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Agent / Kontragent')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hujjat raqami')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Eslatmalar')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Umumiy summa')),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Realizatsiya marjasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taminotchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ta'minotchi nomi")),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': "Ta'minotchi",
                'verbose_name_plural': "Ta'minotchilar",
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.financialcategory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Xarid (Kirim)'), ('SALE', 'Realizatsiya (Chiqim)')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqimlar', to='inventory.maxsulot', verbose_name='Maxsulot')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
            },
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='inventory.olchovbirligi', verbose_name="O'lchov birligi"),
        ),
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(verbose_name='Miqdori')),
                ('oxirgi_narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oxirgi narxi')),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omborlar', to='inventory.maxsulot', verbose_name='Maxsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Ovqat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovqatlar', to='inventory.ovqatkategoriya', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Ovqat',
                'verbose_name_plural': 'Ovqatlar',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Soni')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotib olish narxi')),
                ('margin_percent', models.FloatField(default=0.0, verbose_name='Ustama %')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotish narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryproduct', verbose_name='Mahsulot')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='RealizationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Soni')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotib olish narxi')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotish narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryproduct', verbose_name='Mahsulot')),
                ('realization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.realization')),
            ],
        ),
        migrations.CreateModel(
            name='Retsept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Miqdori')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retseptlar', to='inventory.ovqat', verbose_name='Ovqat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retseptlar', to='inventory.maxsulot', verbose_name='Maxsulot')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
            },
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kirimlar', to='inventory.maxsulot', verbose_name='Maxsulot')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kirimlar', to='inventory.olchovbirligi', verbose_name="O'lchov birligi")),
                ('taminotchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kirimlar', to='inventory.taminotchi', verbose_name="Ta'minotchi")),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Daromad'), ('EXPENSE', 'Xarajat')], max_length=20, verbose_name='Tranzaksiya turi')),
                ('source_type', models.CharField(choices=[('KASSA', 'Kassa'), ('MANUAL', "Qo'lda kiritilgan"), ('BANK', 'Bank')], default='MANUAL', max_length=20, verbose_name='Manba turi')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategoriya')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana va vaqt')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.financialaccount', verbose_name='Hisobga')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-date_created'],
            },
        ),
    ]
