# Generated by Django 4.2.29 on 2026-04-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='min_quantity',
        ),
    ]
