# Generated by Django 4.2.29 on 2026-04-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_ingredient_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
