# Generated by Django 4.2.29 on 2026-04-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_ingredient_min_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='min_quantity',
        ),
    ]
