# Generated by Django 4.2.29 on 2026-04-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('inventory', '0008_remove_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
