# Generated by Django 6.0.3 on 2026-04-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockin_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
    ]
