# Generated by Django 4.2.29 on 2026-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_ingredient_branch_remove_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
            },
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
            },
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OlchovBirligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "O'lchov birligi",
                'verbose_name_plural': "O'lchov birliklari",
            },
        ),
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(verbose_name='Miqdori')),
                ('oxirgi_narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oxirgi narxi')),
            ],
        ),
        migrations.CreateModel(
            name='Ovqat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ovqat',
                'verbose_name_plural': 'Ovqatlar',
            },
        ),
        migrations.CreateModel(
            name='OvqatKategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ovqat kategoriyasi',
                'verbose_name_plural': 'Ovqat kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Retsept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Miqdori')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
            },
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='product',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
