# Generated by Django 4.2.29 on 2026-04-24 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0012_chiqim_kirim_maxsulot_olchovbirligi_ombor_ovqat_and_more'),
        ('table', '0003_remove_productingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.DeleteModel(
            name='StockOut',
        ),
        migrations.AddField(
            model_name='retsept',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retseptlar', to='inventory.ovqat', verbose_name='Ovqat'),
        ),
        migrations.AddField(
            model_name='retsept',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retseptlar', to='inventory.maxsulot', verbose_name='Maxsulot'),
        ),
        migrations.AddField(
            model_name='ovqat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovqatlar', to='inventory.ovqatkategoriya', verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='ombor',
            name='maxsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omborlar', to='inventory.maxsulot', verbose_name='Maxsulot'),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='inventory.olchovbirligi', verbose_name="O'lchov birligi"),
        ),
        migrations.AddField(
            model_name='kirim',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan'),
        ),
        migrations.AddField(
            model_name='kirim',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kirimlar', to='inventory.maxsulot', verbose_name='Maxsulot'),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan'),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqimlar', to='inventory.maxsulot', verbose_name='Maxsulot'),
        ),
    ]
