# Generated by Django 6.0.5 on 2026-07-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('inventory', '0001_initial'),
        ('order', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Filial')),
                ('warehouse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ombor')),
                ('printer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Printer')),
                ('is_print_begunok', models.BooleanField(default=True, verbose_name='Begunokni chop etish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Bo'linma",
                'verbose_name_plural': "Bo'linmalar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('mxik', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('is_active', models.BooleanField(default=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_weight_recipe', models.BooleanField(default=False)),
                ('product_type', models.CharField(default='Taom', max_length=100, verbose_name='Turi')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shtrix-kod')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kitchen.category')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('brutto', models.FloatField()),
                ('netto', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kitchen.food')),
            ],
        ),
        migrations.CreateModel(
            name='MenuProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Taom nomi')),
                ('category', models.CharField(max_length=255, verbose_name='Kategoriya')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotuv narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_products/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status (Aktiv/Pasiv)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Taom Tannarxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.restaurantsection', verbose_name="Bo'linma (Oshxona/Bar)")),
            ],
            options={
                'verbose_name': 'Menyu taomi',
                'verbose_name_plural': 'Menyu taomlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Masalliq/Yarim tayyor mahsulot nomi')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="O'lchov birligi narxi")),
                ('brutto', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Brutto')),
                ('netto', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Netto')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tannarxi')),
                ('menu_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='kitchen.menuproduct', verbose_name='Qaysi taomga tegishli')),
            ],
        ),
        migrations.CreateModel(
            name='SemiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Yarim tayyor mahsulot nomi')),
                ('unit', models.CharField(max_length=50, verbose_name="O'lchov birligi")),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Umumiy Tannarxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.financialcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yarim tayyor mahsulot',
                'verbose_name_plural': 'Yarim tayyor mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemiProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Masalliq nomi')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="O'lchov birligi uchun narx")),
                ('brutto', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Brutto (vazni)')),
                ('netto', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Netto (vazni)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tannarxi')),
                ('semi_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_old', to='kitchen.semiproduct', verbose_name='Qaysi mahsulotga tegishli')),
            ],
        ),
        migrations.CreateModel(
            name='SemiProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Miqdori')),
                ('brutto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('netto', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryproduct', verbose_name='Masalliq (Ombor)')),
                ('semi_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='kitchen.semiproduct')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('COOKING', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('CANCELLED', 'Bekor qilindi')], default='NEW', help_text='Oshxona jarayon holati.', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='Oshxona tayyorlashni boshlagan vaqt.', null=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text='Taom tayyor bo‘lgan vaqt.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ticket yaratilgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish.')),
                ('order', models.OneToOneField(help_text='Bog‘langan buyurtma.', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket', to='order.order')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Ticketni yuborgan xodim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_kitchen_tickets', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='kitchen_kit_status_e5512a_idx'), models.Index(fields=['created_at'], name='kitchen_kit_created_055fec_idx')],
            },
        ),
    ]
