# Generated by Django 6.0.5 on 2026-07-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        ('table', '0003_table_x_table_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255, verbose_name='Masalliq nomi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Miqdori/Sarfi')),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name="O'lchov birligi (kg, litr, dona)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='table.product', verbose_name='Taom/Mahsulot')),
            ],
        ),
    ]
