# Generated by Django 6.0.5 on 2026-07-17 08:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(default='BAHOR CAFE', max_length=100)),
                ('address', models.CharField(default="Toshkent sh., Mustaqillik ko'chasi", max_length=255)),
                ('phone', models.CharField(default='+998901234567', max_length=20)),
                ('footer_text', models.CharField(default="Telegram kanalimizga obuna bo'ling!", max_length=255)),
                ('show_cafe_name', models.BooleanField(default=True)),
                ('show_sana', models.BooleanField(default=True)),
                ('show_ish_vaqti', models.BooleanField(default=True)),
                ('show_sotuvchi', models.BooleanField(default=True)),
                ('show_kassir', models.BooleanField(default=True)),
                ('show_mijoz', models.BooleanField(default=True)),
                ('show_kontaktlar', models.BooleanField(default=True)),
                ('show_inn', models.BooleanField(default=True)),
                ('show_yuridik_shaxs', models.BooleanField(default=True)),
                ('show_manzil', models.BooleanField(default=True)),
                ('show_mijoz_raqami', models.BooleanField(default=True)),
                ('show_eslatma', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True)),
                ('table_number', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dine_in', 'Dine in (zalda)'), ('takeaway', 'Takeaway (olib ketish)'), ('delivery', 'Delivery (yetkazib berish)')], default='dine_in', help_text='Buyurtma turi.', max_length=20)),
                ('number', models.CharField(help_text='Buyurtma raqami. Bir kun ichida takrorlanmaydi.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_kitchen', 'Oshxonaga yuborildi'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('served', 'Berildi'), ('payment_pending', 'To‘lov kutilmoqda'), ('paid', 'To‘lov olindi'), ('closed', 'Yopildi'), ('cancelled', 'Bekor qilindi')], default='draft', help_text='Buyurtmaning joriy holati.', max_length=30)),
                ('guests_count', models.PositiveIntegerField(default=1, help_text='Mehmonlar soni.')),
                ('note', models.TextField(blank=True, default='', help_text='Buyurtmaga umumiy izoh.')),
                ('service_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Servis haqi.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Yakuniy to'lanadigan summa.", max_digits=12)),
                ('sent_to_kitchen_at', models.DateTimeField(blank=True, help_text='Buyurtma oshxonaga yuborilgan vaqt.', null=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text="Buyurtma tayyor bo'lgan vaqt.", null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Buyurtma yopilgan vaqt.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Buyurtma yaratilgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Buyurtma oxirgi marta yangilangan vaqt.')),
                ('assigned_waiter', models.ForeignKey(blank=True, help_text="Mas'ul ofitsiant.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to='employee.employee')),
                ('table', models.ForeignKey(blank=True, help_text="Stol (faqat dine-in bo'lsa to'ladi).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='table.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, default='', help_text='Mahsulot nomining buyurtma paytidagi nusxasi.', max_length=255)),
                ('kitchen_name_snapshot', models.CharField(blank=True, default='', help_text="Oshxona uchun ko'rinadigan nomning nusxasi.", max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Bir dona narxi.', max_digits=12)),
                ('qty', models.PositiveIntegerField(default=1, help_text='Mahsulot soni.')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Umumiy summa = unit_price x qty.', max_digits=14)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('cancelled', 'Bekor qilindi')], default='new', help_text='Item holati.', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Aynan shu item uchun izoh.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi yangilangan vaqt.')),
                ('order', models.ForeignKey(help_text='Qaysi buyurtmaga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(blank=True, help_text="Mahsulot o'chsa NULL bo'ladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='table.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_order_status_2f1723_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_order_created_ffede0_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_order_number'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status'], name='order_order_order_i_b734e6_idx'),
        ),
    ]
