# Generated by Django 6.0.5 on 2026-07-17 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('table', '0002_tablepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_part',
            field=models.ForeignKey(blank=True, help_text="Stolning qismi (agar stol qismiga bo'lingan bo'lsa).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_part', to='table.tablepart'),
        ),
    ]
