# Generated by Django 6.0.5 on 2026-08-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_expensetype_cashtransaction'),
        ('sozlamalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Buyurtma tegishli bo'lgan filial.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sozlamalar.branch'),
        ),
    ]
