# Generated by Django 4.2.29 on 2026-04-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockout_stockin'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ingredients', to='table.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='product',
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
        migrations.DeleteModel(
            name='StockOut',
        ),
    ]
