# Generated by Django 6.0.5 on 2026-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_tablepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='x',
            field=models.FloatField(blank=True, help_text='Stolning xaritadagi x koordinatasi.', null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='y',
            field=models.FloatField(blank=True, help_text='Stolning xaritadagi y koordinatasi.', null=True),
        ),
    ]
