# Generated by Django 4.2.29 on 2026-04-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_chiqim_kirim_maxsulot_olchovbirligi_ombor_ovqat_and_more'),
        ('table', '0002_productingredient_remove_stockout_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='productingredient',
            name='maxsulot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.maxsulot'),
        ),
    ]
