# Generated by Django 6.0.5 on 2026-08-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozlamalar', '0001_initial'),
        ('table', '0003_table_x_table_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Stol tegishli bo'lgan filial.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='sozlamalar.branch'),
        ),
    ]
